### ISSUE TITLE
Home Assistant Python bindings deprecated

### ISSUE THREAD

**Issue by provokateurin** [n8henrie/fauxmo-plugins#11]
https://developers.home-assistant.io/docs/en/external_api_rest_python.html

I'm going to develop a new plugin using the Home Assistant REST API.

**Comment by provokateurin** [comment]
See #12

**Comment by n8henrie** [comment]
As noted, I [pulled in your changes](https://github.com/n8henrie/fauxmo-plugins/commits/dev) and have made a few modifications. Thank you for your contribution!
