### ISSUE TITLE
small typo to be corrected

### ISSUE THREAD

**Issue by dedelajoie** [n8henrie/fauxmo-plugins#13]
hello, 
this is not an issue but just a typo and I don't think it deserves a fork.
so : 
in the fauxmo plugins repository (here : https://github.com/n8henrie/fauxmo-plugins) 
in the file commandlineplugin.py , the example config file is given like this : 

{
  "FAUXMO": {
    "ip_address": "auto"
  },
  "PLUGINS": {
    "CommandLinePlugin": {
      "path": "/path/to/commandlineplugin.py",
      "DEVICES": [
        {
            "name": "output stuff to a file",
            "port": 49915,
            "on_cmd": "touch testfile.txt",
            "off_cmd": "rm testfile.txt",
            "state_cmd": "ls testfile.txt",
        }
      ]
    }
  }
}

but it doesn't work, you have to withdraw the coma at the end of the line 
            "state_cmd": "ls testfile.txt"

this is also an opportunity for me to thank you and congratulate you for this project which is definitly a great achievment ! 

thank you again

**Comment by n8henrie** [comment]
Thanks. I forgot json doesn't like trailing commas (a shame).

Fixed in https://github.com/n8henrie/fauxmo-plugins/commit/3febeea4204631503b77de974392bb32b26c550f
