### ISSUE TITLE
MQTTPlugin: "device doesn't support that" error

### ISSUE THREAD

**Issue by dedelajoie** [n8henrie/fauxmo-plugins#20]
Operating system and version: Raspian 4.14.79-(RPi3)
Python version: 3.7.3 
Fauxmo version (fauxmo --version): v0.5.0
Echo device type : Echo 2nd generation
Echo Firmware Version: 1.24.207453.0 

my config.json is : 
--------------------------------------------------
    "FAUXMO": {
        "ip_address": "auto"
    },
    "PLUGINS": {
        "MQTTPlugin": {
          "path": "/home/pi/fauxmo-plugins/mqttplugin.py",
            "DEVICES": [
                {
                    "port": 12349,
                    "on_cmd": [ "raspmotecli", "BOSE,ON" ],
                    "off_cmd": [ "raspmotecli", "BOSE,OFF" ],
                    "state_cmd": "raspmotecli",
                    "name":"BASE",
                    "mqtt_server": "192.168.1.14",
                    "mqtt_port": 1883
                }
            ]
        }

    }
}
---------------------------------------

when detecting the device, everything works fine
when asking Alexa to turn "ON" or "OFF" the device BASE. Alexa answers "BASE doesn't support that".

what is very surprising is that when runninf fauxmo with -vvv nothing seems to be received from alexa regarding my order. 

I noticed that when BASE is discovered its state is "unknown".  here is what's produced : 

---------------------------------------------------
```
<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetBinaryState xmlns:u="urn:Belkin:service:basicevent:1"><BinaryState>1</BinaryState></u:GetBinaryState></s:Body></s:Envelope>
2020-05-18 00:12:52 fauxmo:66       INFO     request BasicEvent1
2020-05-18 00:12:52 fauxmo:114      DEBUG    Handling action for plugin type <fauxmo.plugins.mqttplugin.MQTTPlugin object at 0x76135df0>
2020-05-18 00:12:52 fauxmo:140      INFO     Attempting to get state for BASE
2020-05-18 00:12:52 fauxmo:146      INFO     BASE state: unknown
2020-05-18 00:12:52 fauxmo:188      WARNING  Unable to complete command for BASE:
POST /upnp/control/basicevent1 HTTP/1.1
SOAPACTION: "urn:Belkin:service:basicevent:1#GetBinaryState"
Content-Type: text/xml; charset="utf-8"
Accept:
User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1.1; AEORD Build/LVY48F)
Host: 192.168.1.26:12349
Connection: Keep-Alive
Accept-Encoding: gzip
Content-Length: 299
```
-------------------------------------------------------

I read other tickets relard to those unknow state but couldn't find out anything that could help me. 

thank you in any case for your work and your answer

**Comment by n8henrie** [comment]
There should be much more content in your verbose log. Can you post the rest?

**Comment by n8henrie** [comment]
Also, I have still never used the mqtt plugin -- any thoughts from @perforex would be appreciated!

**Comment by dedelajoie** [comment]
Thank you for your quick reply. 
using the -v option I found this line when trigerring the discovering : 
"2020-05-18 21:37:15 fauxmo:188      WARNING  Unable to complete command for BASE:"

so I guess I am going to try to get my command "BASE" to work before bothering you. 
I guess you can close this case.

**Comment by n8henrie** [comment]
Sounds good.

Make sure to run with the extra verbose -- `-vvv`

If you're able to get your command working and that fixes the issue, please post back with what you found (for other users).

If you're able to get it working outside of fauxmo and that *doesn't* fix the issue, I'll be happy to re-open.
