### ISSUE TITLE
The mqtt loop should probably always be running

### ISSUE THREAD

**Issue by skorokithakis** [n8henrie/fauxmo-plugins#29]
If I don't run the loop (which I don't, because of state updates), I get "connection closed" errors a lot. I think the loop should run regardless, because I think that's where the keepalive code is.

I can submit a PR if you'd like.

**Comment by jdodgen** [comment]
Yes, it is needed for all the on_* callbacks.  My patch addresses this 
https://github.com/n8henrie/fauxmo-plugins/issues/26#issuecomment-1519191353
