### ISSUE TITLE
MQTT plugin

### ISSUE THREAD

**Issue by Perforex** [n8henrie/fauxmo-plugins#5]
I'm considering writing an MQTT plugin for fauxmo but before I start I'd like to understand how popular this requirement might be. It's popularity won't dictate whether I write the plugin, since I need it for my own use, but rather the care, testing and functionality that I include. For example I don't need features such as user authentication or QoS since I'm only using MQTT on my internal network and very low volume but if these are features useful to a lot of other people, I'll consider it during the design phase.    

Though I haven't been a professional code writer for many years, having looked at the existing plugins and the guidelines I don't think it will be an onerous task. 

I'd welcome all feedback on this proposal/suggestion.

**Comment by SupraJames** [comment]
I am here looking for an MQTT plugin and my requirements are kinda like yours. I don't care (much) about security, if someone's on my internal network they are welcome to control my lights!

If you do hack something together, please let me know, and I'd be happy to test.

**Comment by n8henrie** [comment]
I think an MQTT plugin would be sweet. I don't use it a whole lot, but I know the IOT community seems to love it overall.

FYI, for the few MQTT devices I *do* use, I have them integrated through Home Assistant by way of mosquitto, and Fauxmo works with them just fine through the Home Assistant plugin.

For people not interested in running things through Home Assistant, a direct MQTT plugin would probably be much appreciated.

**Comment by Perforex** [comment]
@SupraJames - Thanks, I'll certainly keep you up to date on progress and testing would me much appreciated.
@n8henrie - Thanks, I'm sort of in the second boat, I already have devices that work well through MQTT and whilst I could use Home Assistant, I'd rather not go down that route.

**Comment by Perforex** [comment]
@n8henrie 
Code developed and tested, looking good so far but external testing is welcomed. 

A couple of questions for  you:

- Do you need to add me as a contributor before I have write access to create a Pull Request or is the default write?
- I've introduced a new module (paho-mqtt) and I'm not sure how that should be handled in terms of packaging. Advice and guidance welcomed.

Help with these two gratefully received.

**Comment by SupraJames** [comment]
Maybe fork n8henrie’s project?

You can then make local changes, I can test too, and then you’d submit a pull request to the main project.

Cheers
James

**Comment by n8henrie** [comment]
@Perforex awesome!

1. No, like most GitHub repos, anyone can make a pull request. This allows everyone to review the changes before they are merged and for the continuous integration tests to run (if any).
2. Dependencies (and pinned version numbers) should be added to the module-level docstring. Search the readme for `dependenc`, see my examples, and let me know how I can further clarify.

**Comment by Perforex** [comment]
Thank you both for your help and advice. As you can probably tell I'm new to the collaborative use of git but it's a great learning experience. I've forked the plugin, added the new module (including the docstring for dependencies) and raised the pull request. #6 

I hope this is all as per convention and I look forward to the next stage in the process. :-)

**Comment by n8henrie** [comment]
Yes, this is how things usually work, thanks for your contribution.

I’m busy at work the next couple days but will take a look at the PR as soon as I can.

**Comment by SupraJames** [comment]
Perforex, just testing this and it is also working for me, so thanks!

I do see that your code is connecting, publishing, and disconnecting to the MQTT server for each call, which doesn't seem ideal, but I'm equally new to this.

Perhaps you can do self.client = mqtt.Client() and self.client.connect(self.qserver,self.qport,60) in __init__ and just publish messages in the handlers for on and off.

I've tested locally that change and seems to work OK. I'm supposing that the MQTT library itself will take care of re-connecting to the broker as required.

**Comment by Perforex** [comment]
@SupraJames 
Thanks James, glad it's working. I've just had a look at your changes and I like your thinking, it does seem more efficient to do the connection once. I'll merge your changes so that it can be incorporated into the final pull request. (I think that's the way it's supposed to happen...)

@n8henrie 
Please advise if we're doing this right, thanks.

**Comment by n8henrie** [comment]
Doing what right? The PR?

I'm no expert on the MQTT part.

Will review your new PR when you submit.

**Comment by n8henrie** [comment]
Merged into dev with https://github.com/n8henrie/fauxmo-plugins/commit/d2cfea32e38359b77d58e2db75062a1a18617335
